
from aiogram.types import ReplyKeyboardRemove, ReplyKeyboardMarkup, KeyboardButton, InlineKeyboardMarkup, InlineKeyboardButton




btn_1 = KeyboardButton('Розмістити оголошення 🚗')
greet_kb = ReplyKeyboardMarkup(resize_keyboard = True).add(btn_1)


btn_2 = KeyboardButton('Додати фото ✅')
addphoto_kb = ReplyKeyboardMarkup(resize_keyboard = True).add(btn_2)


btn_city_1 = KeyboardButton('Вінниця і область')
btn_city_2 = KeyboardButton('Дніпро і область')
btn_city_3 = KeyboardButton('Донецьк і область')
btn_city_4 = KeyboardButton('Житомир і область')
btn_city_5 = KeyboardButton('Запоріжжя і область')
btn_city_6 = KeyboardButton('Івано-Франківськ і область')
btn_city_7 = KeyboardButton('Київ і область')
btn_city_8 = KeyboardButton('Кропивницький і область')
btn_city_9 = KeyboardButton('Луганськ і область')
btn_city_10 = KeyboardButton('Луцьк і область')
btn_city_11 = KeyboardButton('Львів і область')
btn_city_12 = KeyboardButton('Миколаїв і область')
btn_city_13 = KeyboardButton('Одеса і область')
btn_city_14 = KeyboardButton('Полтава і область')
btn_city_15 = KeyboardButton('Рівне і область')
btn_city_16 = KeyboardButton('Суми і область')
btn_city_17 = KeyboardButton('Тернопіль і область')
btn_city_18 = KeyboardButton('Ужгород і область')
btn_city_19 = KeyboardButton('Харків і область')
btn_city_20 = KeyboardButton('Херсон і область')
btn_city_21 = KeyboardButton('Хмельницький і область')
btn_city_22 = KeyboardButton('Черкаси і область')
btn_city_23 = KeyboardButton('Чернівці і область')
btn_city_24 = KeyboardButton('Чернігів і область')


city_kb = ReplyKeyboardMarkup(resize_keyboard = True).add(btn_city_1,btn_city_2,btn_city_3,btn_city_4,btn_city_5,btn_city_6,btn_city_7,btn_city_8,btn_city_9,btn_city_10,btn_city_11,btn_city_12,btn_city_13,btn_city_14,btn_city_15,btn_city_16,btn_city_17,btn_city_18,btn_city_19,btn_city_20,btn_city_21,btn_city_22,btn_city_23,btn_city_24)






btn_auto_1 = KeyboardButton('Acura')
btn_auto_2 = KeyboardButton('Alfa Romeo')
btn_auto_3 = KeyboardButton('Audi')
btn_auto_4 = KeyboardButton('BMW')
btn_auto_5 = KeyboardButton('Brilliance')
btn_auto_6 = KeyboardButton('BYD')
btn_auto_7 = KeyboardButton('Cadillac')
btn_auto_8 = KeyboardButton('Chana')
btn_auto_9 = KeyboardButton('ChangFeng')
btn_auto_10 = KeyboardButton('Chery')
btn_auto_11 = KeyboardButton('Chevrolet')
btn_auto_12 = KeyboardButton('Chrysler')
btn_auto_13 = KeyboardButton('Citroen')
btn_auto_14= KeyboardButton('Dacia')
btn_auto_15 = KeyboardButton('Dadi')
btn_auto_16 = KeyboardButton('Daewoo')
btn_auto_17 = KeyboardButton('Daihatsu')
btn_auto_18 = KeyboardButton('Dodge')
btn_auto_19 = KeyboardButton('Ferrari')
btn_auto_20 = KeyboardButton('Fiat')
btn_auto_21 = KeyboardButton('Ford')
btn_auto_22 = KeyboardButton('Geely')
btn_auto_23 = KeyboardButton('GMC')
btn_auto_24 = KeyboardButton('Great Wall')
btn_auto_25 = KeyboardButton('Honda')
btn_auto_26 = KeyboardButton('Hummer')
btn_auto_27 = KeyboardButton('Hyundai')
btn_auto_28 = KeyboardButton('Infiniti')
btn_auto_29 = KeyboardButton('Isuzu')
btn_auto_30 = KeyboardButton('Iveco')
btn_auto_31 = KeyboardButton('JAC')
btn_auto_32 = KeyboardButton('Jaguar')
btn_auto_33 = KeyboardButton('Jeep')
btn_auto_34 = KeyboardButton('Kia')
btn_auto_35 = KeyboardButton('Lancia')
btn_auto_36 = KeyboardButton('Land Rover')
btn_auto_37 = KeyboardButton('Lexus')
btn_auto_38 = KeyboardButton('Lifan')
btn_auto_39 = KeyboardButton('Lincoln')
btn_auto_40 = KeyboardButton('Maserati')
btn_auto_41 = KeyboardButton('Mazda')
btn_auto_42 = KeyboardButton('Mercedes-Benz')
btn_auto_43 = KeyboardButton('MG')
btn_auto_44 = KeyboardButton('MINI')
btn_auto_45 = KeyboardButton('Mitsubishi')
btn_auto_46 = KeyboardButton('Nissan')
btn_auto_47 = KeyboardButton('Oldsmobile')
btn_auto_48 = KeyboardButton('Opel')
btn_auto_49 = KeyboardButton('Peugeot')
btn_auto_50 = KeyboardButton('Pontiac')
btn_auto_51 = KeyboardButton('Porsche')
btn_auto_52 = KeyboardButton('Ravon')
btn_auto_53 = KeyboardButton('Renault')
btn_auto_54 = KeyboardButton('Roewe')
btn_auto_55 = KeyboardButton('Rover')
btn_auto_56 = KeyboardButton('Saab')
btn_auto_57 = KeyboardButton('Samand')
btn_auto_58 = KeyboardButton('Seat')
btn_auto_59 = KeyboardButton('Skoda')
btn_auto_60 = KeyboardButton('Smart')
btn_auto_61 = KeyboardButton('SsangYong')
btn_auto_62 = KeyboardButton('Subaru')
btn_auto_63 = KeyboardButton('Suzuki')
btn_auto_64 = KeyboardButton('Tesla')
btn_auto_65 = KeyboardButton('Toyota')
btn_auto_66 = KeyboardButton('Volkswagen')
btn_auto_67 = KeyboardButton('Volvo')
btn_auto_68 = KeyboardButton('Wartburg')
btn_auto_69 = KeyboardButton('ZX')
btn_auto_70 = KeyboardButton('Богдан')
btn_auto_71 = KeyboardButton('ВАЗ')
btn_auto_72 = KeyboardButton('ГАЗ')
btn_auto_73 = KeyboardButton('ЗАЗ')
btn_auto_74 = KeyboardButton('ИЖ')
btn_auto_75 = KeyboardButton('ЛуАЗ')
btn_auto_76 = KeyboardButton('Москвич / АЗЛК')
btn_auto_77 = KeyboardButton('РАФ')
btn_auto_78 = KeyboardButton('УАЗ')
btn_auto_79 = KeyboardButton('Інші')
btn_auto_80 = KeyboardButton('Bentley')

auto_kb = ReplyKeyboardMarkup(resize_keyboard = True).add(btn_auto_1,btn_auto_2,btn_auto_3,btn_auto_80,btn_auto_4,btn_auto_5,btn_auto_6,btn_auto_7,btn_auto_8,btn_auto_9,btn_auto_10,btn_auto_11,btn_auto_12,btn_auto_13,btn_auto_14,btn_auto_15,btn_auto_16,btn_auto_17,btn_auto_18,btn_auto_19,btn_auto_20,btn_auto_21,btn_auto_22,btn_auto_23,btn_auto_24,btn_auto_25,btn_auto_26,btn_auto_27,btn_auto_28,btn_auto_29,btn_auto_30,btn_auto_31,btn_auto_32,btn_auto_33,btn_auto_34,btn_auto_35,btn_auto_36,btn_auto_37,btn_auto_38,btn_auto_39,btn_auto_40,btn_auto_41,btn_auto_42,btn_auto_43,btn_auto_44,btn_auto_45,btn_auto_46,btn_auto_47,btn_auto_48,btn_auto_49,btn_auto_50,btn_auto_51,btn_auto_52,btn_auto_53,btn_auto_54,btn_auto_55,btn_auto_56,btn_auto_57,btn_auto_58,btn_auto_59,btn_auto_60,btn_auto_61,btn_auto_62,btn_auto_63,btn_auto_64,btn_auto_65,btn_auto_66,btn_auto_67,btn_auto_68,btn_auto_69,btn_auto_70,btn_auto_71,btn_auto_72,btn_auto_73,btn_auto_74,btn_auto_75,btn_auto_76,btn_auto_77,btn_auto_78,btn_auto_79)




btn_per_1 = KeyboardButton('Механічна')
btn_per_2 = KeyboardButton('Автоматична')
btn_per_3 = KeyboardButton('Варіатор')
btn_per_4 = KeyboardButton('Адаптивна')
btn_per_5 = KeyboardButton('Типтронік')


per_kb = ReplyKeyboardMarkup(resize_keyboard = True).add(btn_per_1,btn_per_2,btn_per_3,btn_per_4,btn_per_5)

